version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "countVisitors"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k7g7ga41954b"
s3_prefix = "countVisitors"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
